//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class RotateBoneAnimationComponent : EditorActorComponent {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal RotateBoneAnimationComponent(global::System.IntPtr cPtr, bool cMemoryOwn) : base(EditorRendererPINVOKE.RotateBoneAnimationComponent_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(RotateBoneAnimationComponent obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          EditorRendererPINVOKE.delete_RotateBoneAnimationComponent(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public override void Update(float DeltaTime, float TotalTime) {
    EditorRendererPINVOKE.RotateBoneAnimationComponent_Update(swigCPtr, DeltaTime, TotalTime);
  }

  public override void Destroy() {
    EditorRendererPINVOKE.RotateBoneAnimationComponent_Destroy(swigCPtr);
  }

  public void StartAnimation(string inBoneName, float inSpeed, RotateBoneAnimationAxis inAxis) {
    EditorRendererPINVOKE.RotateBoneAnimationComponent_StartAnimation(swigCPtr, inBoneName, inSpeed, (int)inAxis);
    if (EditorRendererPINVOKE.SWIGPendingException.Pending) throw EditorRendererPINVOKE.SWIGPendingException.Retrieve();
  }

  public void PauseAnimation() {
    EditorRendererPINVOKE.RotateBoneAnimationComponent_PauseAnimation(swigCPtr);
  }

  public void ResumeAnimation() {
    EditorRendererPINVOKE.RotateBoneAnimationComponent_ResumeAnimation(swigCPtr);
  }

  public void StopAnimation() {
    EditorRendererPINVOKE.RotateBoneAnimationComponent_StopAnimation(swigCPtr);
  }

  public RotateBoneAnimationComponent() : this(EditorRendererPINVOKE.new_RotateBoneAnimationComponent(), true) {
  }

}
