//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public class EditorActorComponent : EditorRendererObject {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal EditorActorComponent(global::System.IntPtr cPtr, bool cMemoryOwn) : base(EditorRendererPINVOKE.EditorActorComponent_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(EditorActorComponent obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          EditorRendererPINVOKE.delete_EditorActorComponent(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public virtual void Update(float DeltaTime, float TotalTime) {
    EditorRendererPINVOKE.EditorActorComponent_Update(swigCPtr, DeltaTime, TotalTime);
  }

  public override void Destroy() {
    EditorRendererPINVOKE.EditorActorComponent_Destroy(swigCPtr);
  }

  public EditorActorComponent() : this(EditorRendererPINVOKE.new_EditorActorComponent(), true) {
  }

}
