//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


class EditorRendererPINVOKE {

  protected class SWIGExceptionHelper {

    public delegate void ExceptionDelegate(string message);
    public delegate void ExceptionArgumentDelegate(string message, string paramName);

    static ExceptionDelegate applicationDelegate = new ExceptionDelegate(SetPendingApplicationException);
    static ExceptionDelegate arithmeticDelegate = new ExceptionDelegate(SetPendingArithmeticException);
    static ExceptionDelegate divideByZeroDelegate = new ExceptionDelegate(SetPendingDivideByZeroException);
    static ExceptionDelegate indexOutOfRangeDelegate = new ExceptionDelegate(SetPendingIndexOutOfRangeException);
    static ExceptionDelegate invalidCastDelegate = new ExceptionDelegate(SetPendingInvalidCastException);
    static ExceptionDelegate invalidOperationDelegate = new ExceptionDelegate(SetPendingInvalidOperationException);
    static ExceptionDelegate ioDelegate = new ExceptionDelegate(SetPendingIOException);
    static ExceptionDelegate nullReferenceDelegate = new ExceptionDelegate(SetPendingNullReferenceException);
    static ExceptionDelegate outOfMemoryDelegate = new ExceptionDelegate(SetPendingOutOfMemoryException);
    static ExceptionDelegate overflowDelegate = new ExceptionDelegate(SetPendingOverflowException);
    static ExceptionDelegate systemDelegate = new ExceptionDelegate(SetPendingSystemException);

    static ExceptionArgumentDelegate argumentDelegate = new ExceptionArgumentDelegate(SetPendingArgumentException);
    static ExceptionArgumentDelegate argumentNullDelegate = new ExceptionArgumentDelegate(SetPendingArgumentNullException);
    static ExceptionArgumentDelegate argumentOutOfRangeDelegate = new ExceptionArgumentDelegate(SetPendingArgumentOutOfRangeException);

    [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="SWIGRegisterExceptionCallbacks_EditorRenderer")]
    public static extern void SWIGRegisterExceptionCallbacks_EditorRenderer(
                                ExceptionDelegate applicationDelegate,
                                ExceptionDelegate arithmeticDelegate,
                                ExceptionDelegate divideByZeroDelegate, 
                                ExceptionDelegate indexOutOfRangeDelegate, 
                                ExceptionDelegate invalidCastDelegate,
                                ExceptionDelegate invalidOperationDelegate,
                                ExceptionDelegate ioDelegate,
                                ExceptionDelegate nullReferenceDelegate,
                                ExceptionDelegate outOfMemoryDelegate, 
                                ExceptionDelegate overflowDelegate, 
                                ExceptionDelegate systemExceptionDelegate);

    [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="SWIGRegisterExceptionArgumentCallbacks_EditorRenderer")]
    public static extern void SWIGRegisterExceptionCallbacksArgument_EditorRenderer(
                                ExceptionArgumentDelegate argumentDelegate,
                                ExceptionArgumentDelegate argumentNullDelegate,
                                ExceptionArgumentDelegate argumentOutOfRangeDelegate);

    static void SetPendingApplicationException(string message) {
      SWIGPendingException.Set(new global::System.ApplicationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArithmeticException(string message) {
      SWIGPendingException.Set(new global::System.ArithmeticException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingDivideByZeroException(string message) {
      SWIGPendingException.Set(new global::System.DivideByZeroException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIndexOutOfRangeException(string message) {
      SWIGPendingException.Set(new global::System.IndexOutOfRangeException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidCastException(string message) {
      SWIGPendingException.Set(new global::System.InvalidCastException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingInvalidOperationException(string message) {
      SWIGPendingException.Set(new global::System.InvalidOperationException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingIOException(string message) {
      SWIGPendingException.Set(new global::System.IO.IOException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingNullReferenceException(string message) {
      SWIGPendingException.Set(new global::System.NullReferenceException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOutOfMemoryException(string message) {
      SWIGPendingException.Set(new global::System.OutOfMemoryException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingOverflowException(string message) {
      SWIGPendingException.Set(new global::System.OverflowException(message, SWIGPendingException.Retrieve()));
    }
    static void SetPendingSystemException(string message) {
      SWIGPendingException.Set(new global::System.SystemException(message, SWIGPendingException.Retrieve()));
    }

    static void SetPendingArgumentException(string message, string paramName) {
      SWIGPendingException.Set(new global::System.ArgumentException(message, paramName, SWIGPendingException.Retrieve()));
    }
    static void SetPendingArgumentNullException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentNullException(paramName, message));
    }
    static void SetPendingArgumentOutOfRangeException(string message, string paramName) {
      global::System.Exception e = SWIGPendingException.Retrieve();
      if (e != null) message = message + " Inner Exception: " + e.Message;
      SWIGPendingException.Set(new global::System.ArgumentOutOfRangeException(paramName, message));
    }

    static SWIGExceptionHelper() {
      SWIGRegisterExceptionCallbacks_EditorRenderer(
                                applicationDelegate,
                                arithmeticDelegate,
                                divideByZeroDelegate,
                                indexOutOfRangeDelegate,
                                invalidCastDelegate,
                                invalidOperationDelegate,
                                ioDelegate,
                                nullReferenceDelegate,
                                outOfMemoryDelegate,
                                overflowDelegate,
                                systemDelegate);

      SWIGRegisterExceptionCallbacksArgument_EditorRenderer(
                                argumentDelegate,
                                argumentNullDelegate,
                                argumentOutOfRangeDelegate);
    }
  }

  protected static SWIGExceptionHelper swigExceptionHelper = new SWIGExceptionHelper();

  public class SWIGPendingException {
    [global::System.ThreadStatic]
    private static global::System.Exception pendingException = null;
    private static int numExceptionsPending = 0;
    private static global::System.Object exceptionsLock = null;

    public static bool Pending {
      get {
        bool pending = false;
        if (numExceptionsPending > 0)
          if (pendingException != null)
            pending = true;
        return pending;
      } 
    }

    public static void Set(global::System.Exception e) {
      if (pendingException != null)
        throw new global::System.ApplicationException("FATAL: An earlier pending exception from unmanaged code was missed and thus not thrown (" + pendingException.ToString() + ")", e);
      pendingException = e;
      lock(exceptionsLock) {
        numExceptionsPending++;
      }
    }

    public static global::System.Exception Retrieve() {
      global::System.Exception e = null;
      if (numExceptionsPending > 0) {
        if (pendingException != null) {
          e = pendingException;
          pendingException = null;
          lock(exceptionsLock) {
            numExceptionsPending--;
          }
        }
      }
      return e;
    }

    static SWIGPendingException() {
      exceptionsLock = new global::System.Object();
    }
  }


  protected class SWIGStringHelper {

    public delegate string SWIGStringDelegate(string message);
    static SWIGStringDelegate stringDelegate = new SWIGStringDelegate(CreateString);

    [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="SWIGRegisterStringCallback_EditorRenderer")]
    public static extern void SWIGRegisterStringCallback_EditorRenderer(SWIGStringDelegate stringDelegate);

    static string CreateString(string cString) {
      return cString;
    }

    static SWIGStringHelper() {
      SWIGRegisterStringCallback_EditorRenderer(stringDelegate);
    }
  }

  static protected SWIGStringHelper swigStringHelper = new SWIGStringHelper();


  static EditorRendererPINVOKE() {
  }


  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorRendererSubsystem_Init")]
  public static extern void EditorRendererSubsystem_Init(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorRendererSubsystem_Shutdown")]
  public static extern void EditorRendererSubsystem_Shutdown(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorRendererSubsystem_CreateEditorViewport")]
  public static extern global::System.IntPtr EditorRendererSubsystem_CreateEditorViewport(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorRendererSubsystem_IsActive")]
  public static extern bool EditorRendererSubsystem_IsActive(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorRendererSubsystem_Render")]
  public static extern bool EditorRendererSubsystem_Render(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorRendererSubsystem_GetPUTemplatesCount")]
  public static extern int EditorRendererSubsystem_GetPUTemplatesCount(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorRendererSubsystem_GetPUTemplatesAtIndex")]
  public static extern string EditorRendererSubsystem_GetPUTemplatesAtIndex(global::System.Runtime.InteropServices.HandleRef jarg1, int jarg2);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_new_EditorRendererSubsystem")]
  public static extern global::System.IntPtr new_EditorRendererSubsystem();

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_delete_EditorRendererSubsystem")]
  public static extern void delete_EditorRendererSubsystem(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorViewport_Create")]
  public static extern bool EditorViewport_Create(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorViewport_Destroy")]
  public static extern void EditorViewport_Destroy(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorViewport_SetWorld")]
  public static extern void EditorViewport_SetWorld(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorViewport_WindowMovedOrResized")]
  public static extern void EditorViewport_WindowMovedOrResized(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorViewport_GetWorld")]
  public static extern global::System.IntPtr EditorViewport_GetWorld(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorViewport_CreateWorld")]
  public static extern global::System.IntPtr EditorViewport_CreateWorld(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorViewport_SetCameraYawPitchDistance")]
  public static extern void EditorViewport_SetCameraYawPitchDistance(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2, float jarg3, float jarg4);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorViewport_SetCameraDistance")]
  public static extern void EditorViewport_SetCameraDistance(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorViewport_SetCameraYaw")]
  public static extern void EditorViewport_SetCameraYaw(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorViewport_SetCameraPitch")]
  public static extern void EditorViewport_SetCameraPitch(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_new_EditorViewport")]
  public static extern global::System.IntPtr new_EditorViewport();

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_delete_EditorViewport")]
  public static extern void delete_EditorViewport(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorWorld_CreateActor")]
  public static extern global::System.IntPtr EditorWorld_CreateActor(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorWorld_Init")]
  public static extern void EditorWorld_Init(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorWorld_Destroy")]
  public static extern void EditorWorld_Destroy(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_new_EditorWorld")]
  public static extern global::System.IntPtr new_EditorWorld();

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_delete_EditorWorld")]
  public static extern void delete_EditorWorld(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorRendererObject_SetName")]
  public static extern void EditorRendererObject_SetName(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorRendererObject_GetName")]
  public static extern string EditorRendererObject_GetName(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorRendererObject_SetWorldPosition")]
  public static extern void EditorRendererObject_SetWorldPosition(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2, float jarg3, float jarg4);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorRendererObject_GetWorldPositionX")]
  public static extern float EditorRendererObject_GetWorldPositionX(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorRendererObject_GetWorldPositionY")]
  public static extern float EditorRendererObject_GetWorldPositionY(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorRendererObject_GetWorldPositionZ")]
  public static extern float EditorRendererObject_GetWorldPositionZ(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorRendererObject_SetRelativePosition")]
  public static extern void EditorRendererObject_SetRelativePosition(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2, float jarg3, float jarg4);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorRendererObject_GetRelativePositionX")]
  public static extern float EditorRendererObject_GetRelativePositionX(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorRendererObject_GetRelativePositionY")]
  public static extern float EditorRendererObject_GetRelativePositionY(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorRendererObject_GetRelativePositionZ")]
  public static extern float EditorRendererObject_GetRelativePositionZ(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorRendererObject_SetWorldRotation")]
  public static extern void EditorRendererObject_SetWorldRotation(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2, float jarg3, float jarg4);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorRendererObject_GetWorldRotationYaw")]
  public static extern float EditorRendererObject_GetWorldRotationYaw(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorRendererObject_GetWorldRotationPitch")]
  public static extern float EditorRendererObject_GetWorldRotationPitch(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorRendererObject_GetWorldRotationRoll")]
  public static extern float EditorRendererObject_GetWorldRotationRoll(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorRendererObject_SetRelativeRotation")]
  public static extern void EditorRendererObject_SetRelativeRotation(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2, float jarg3, float jarg4);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorRendererObject_GetRelativeRotationYaw")]
  public static extern float EditorRendererObject_GetRelativeRotationYaw(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorRendererObject_GetRelativeRotationPitch")]
  public static extern float EditorRendererObject_GetRelativeRotationPitch(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorRendererObject_GetRelativeRotationRoll")]
  public static extern float EditorRendererObject_GetRelativeRotationRoll(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorRendererObject_GetWorld")]
  public static extern global::System.IntPtr EditorRendererObject_GetWorld(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorRendererObject_SetWorld")]
  public static extern void EditorRendererObject_SetWorld(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorRendererObject_SetParent")]
  public static extern void EditorRendererObject_SetParent(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorRendererObject_GetParent")]
  public static extern global::System.IntPtr EditorRendererObject_GetParent(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorRendererObject_GetBoundingRadius")]
  public static extern float EditorRendererObject_GetBoundingRadius(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorRendererObject_Destroy")]
  public static extern void EditorRendererObject_Destroy(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_new_EditorRendererObject")]
  public static extern global::System.IntPtr new_EditorRendererObject();

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_delete_EditorRendererObject")]
  public static extern void delete_EditorRendererObject(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorActor_SetMesh")]
  public static extern void EditorActor_SetMesh(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorActor_GetMeshName")]
  public static extern string EditorActor_GetMeshName(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorActor_GetBoundingRadius")]
  public static extern float EditorActor_GetBoundingRadius(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorActor_Destroy")]
  public static extern void EditorActor_Destroy(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorActor_RegisterForUpdate")]
  public static extern void EditorActor_RegisterForUpdate(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorActor_Update")]
  public static extern void EditorActor_Update(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2, float jarg3);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorActor_CreateChildActor")]
  public static extern global::System.IntPtr EditorActor_CreateChildActor(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorActor_DestroyChildActor")]
  public static extern void EditorActor_DestroyChildActor(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorActor_DestroyChildActorByName")]
  public static extern void EditorActor_DestroyChildActorByName(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorActor_RemoveChildActor")]
  public static extern void EditorActor_RemoveChildActor(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorActor_RemoveChildActorByName")]
  public static extern void EditorActor_RemoveChildActorByName(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorActor_GetChildActorByName")]
  public static extern global::System.IntPtr EditorActor_GetChildActorByName(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorActor_CreateRotateBoneAnimationComponent")]
  public static extern global::System.IntPtr EditorActor_CreateRotateBoneAnimationComponent(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorActor_CreatePUSystemComponent")]
  public static extern global::System.IntPtr EditorActor_CreatePUSystemComponent(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, string jarg3, bool jarg4);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorActor_GetComponent")]
  public static extern global::System.IntPtr EditorActor_GetComponent(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorActor_RemoveComponent")]
  public static extern void EditorActor_RemoveComponent(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorActor_DestroyComponent")]
  public static extern void EditorActor_DestroyComponent(global::System.Runtime.InteropServices.HandleRef jarg1, global::System.Runtime.InteropServices.HandleRef jarg2);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorActor_RemoveComponentByName")]
  public static extern void EditorActor_RemoveComponentByName(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorActor_DestroyComponentByName")]
  public static extern void EditorActor_DestroyComponentByName(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_new_EditorActor")]
  public static extern global::System.IntPtr new_EditorActor();

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_delete_EditorActor")]
  public static extern void delete_EditorActor(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorActorComponent_Update")]
  public static extern void EditorActorComponent_Update(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2, float jarg3);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorActorComponent_Destroy")]
  public static extern void EditorActorComponent_Destroy(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_new_EditorActorComponent")]
  public static extern global::System.IntPtr new_EditorActorComponent();

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_delete_EditorActorComponent")]
  public static extern void delete_EditorActorComponent(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_RotateBoneAnimationComponent_Update")]
  public static extern void RotateBoneAnimationComponent_Update(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2, float jarg3);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_RotateBoneAnimationComponent_Destroy")]
  public static extern void RotateBoneAnimationComponent_Destroy(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_RotateBoneAnimationComponent_StartAnimation")]
  public static extern void RotateBoneAnimationComponent_StartAnimation(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2, float jarg3, int jarg4);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_RotateBoneAnimationComponent_PauseAnimation")]
  public static extern void RotateBoneAnimationComponent_PauseAnimation(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_RotateBoneAnimationComponent_ResumeAnimation")]
  public static extern void RotateBoneAnimationComponent_ResumeAnimation(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_RotateBoneAnimationComponent_StopAnimation")]
  public static extern void RotateBoneAnimationComponent_StopAnimation(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_new_RotateBoneAnimationComponent")]
  public static extern global::System.IntPtr new_RotateBoneAnimationComponent();

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_delete_RotateBoneAnimationComponent")]
  public static extern void delete_RotateBoneAnimationComponent(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_PUSystemComponent_Update")]
  public static extern void PUSystemComponent_Update(global::System.Runtime.InteropServices.HandleRef jarg1, float jarg2, float jarg3);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_PUSystemComponent_Destroy")]
  public static extern void PUSystemComponent_Destroy(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_PUSystemComponent_SetSystemByTemplate")]
  public static extern void PUSystemComponent_SetSystemByTemplate(global::System.Runtime.InteropServices.HandleRef jarg1, string jarg2);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_PUSystemComponent_SetForcedLooping")]
  public static extern void PUSystemComponent_SetForcedLooping(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_PUSystemComponent_PlaySystem")]
  public static extern void PUSystemComponent_PlaySystem(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_PUSystemComponent_StopSystem")]
  public static extern void PUSystemComponent_StopSystem(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_PUSystemComponent_ResetSystem")]
  public static extern void PUSystemComponent_ResetSystem(global::System.Runtime.InteropServices.HandleRef jarg1, bool jarg2);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_PUSystemComponent_GetPUSystemName")]
  public static extern string PUSystemComponent_GetPUSystemName(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_new_PUSystemComponent")]
  public static extern global::System.IntPtr new_PUSystemComponent();

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_delete_PUSystemComponent")]
  public static extern void delete_PUSystemComponent(global::System.Runtime.InteropServices.HandleRef jarg1);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorActor_SWIGUpcast")]
  public static extern global::System.IntPtr EditorActor_SWIGUpcast(global::System.IntPtr jarg1);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_EditorActorComponent_SWIGUpcast")]
  public static extern global::System.IntPtr EditorActorComponent_SWIGUpcast(global::System.IntPtr jarg1);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_RotateBoneAnimationComponent_SWIGUpcast")]
  public static extern global::System.IntPtr RotateBoneAnimationComponent_SWIGUpcast(global::System.IntPtr jarg1);

  [global::System.Runtime.InteropServices.DllImport("EditorRenderer", EntryPoint="CSharp_PUSystemComponent_SWIGUpcast")]
  public static extern global::System.IntPtr PUSystemComponent_SWIGUpcast(global::System.IntPtr jarg1);
}
